# Generated by Django 5.2.17 on 2026-09-22 16:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotebookPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_number', models.PositiveIntegerField()),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('subheading', models.CharField(blank=True, max_length=255)),
                ('content', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='notebooks.notebook')),
            ],
            options={
                'ordering': ['page_number'],
            },
        ),
        migrations.CreateModel(
            name='NotebookPageImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('width', models.FloatField(default=30)),
                ('aspect_ratio', models.FloatField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='notebooks.notebookpage')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='notebookpage',
            index=models.Index(fields=['notebook', 'page_number'], name='notebooks_n_noteboo_8cd066_idx'),
        ),
        migrations.AddConstraint(
            model_name='notebookpage',
            constraint=models.UniqueConstraint(fields=('notebook', 'page_number'), name='unique_notebook_page_number'),
        ),
    ]
