# Generated by Django 5.2.17 on 2026-09-24 08:03

import notebooks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0004_image_page_config_remove_notebookpageimage'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='image',
            new_name='notebooks_i_owner_i_719e26_idx',
            old_name='notebooks_i_owner_i_6f0f0a_idx',
        ),
        migrations.AlterField(
            model_name='notebookpage',
            name='config',
            field=models.JSONField(blank=True, default=notebooks.models.default_page_config),
        ),
    ]
