# Generated by Django 5.2.17 on 2026-09-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0005_rename_notebooks_i_owner_i_6f0f0a_idx_notebooks_i_owner_i_719e26_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='aspect_ratio',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='image',
            name='height',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='width',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
